# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39d7067fdff509538beb46bbfbf8a6bff67632e8726630e9ffd4e118241f614f6e9340829fe8758d22a1df762001c39301c3bb0b8577cbb538957684b3d022d0

test:
  secret_key_base: 6ac4c7c693f7b3ee54962183476ecdfe63d0176288ad7f0aade38bd65698b33f220ca09eec0b58a22d9696a320b647c7c3cd45eab0affef88a365faecea107b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
